# fly.toml app configuration file generated for dify-chat-backend on 2025-01-25T09:04:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dify-chat-backend'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  DATABASE_URL = 'sqlite+aiosqlite:///data/chat.db'

[mounts]
  source = "dify_chat_data"
  destination = "/data"
  initial_size = "1GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
